 name: lrose-hub
 channels:
   - conda-forge
 dependencies:
   - aiohttp
   - arm_pyart
   - cartopy
   - cmweather
   - ipykernel
   - jupyter
   - jupyterlab
   - matplotlib
   - metpy
   - numpy
   - requests
   - seaborn
   - xarray
   - xradar
   - zarr
