
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hub-to-apiserver
spec:
  endpointSelector:
    matchLabels:
      app: jupyterhub
      component: hub
      release: lrose-jhub
  egress:
    - toEntities:
        - kube-apiserver
