
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lrose-jhub-secrets-esos
  namespace: eol-lrose
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lrose-ro
    kind: SecretStore
  target:
    name: lrose-hub-secrets
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: eol-lrose/hub
        property: github_client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: eol-lrose/hub
        property: github_client_secret
